### ISSUE TITLE
Put the first class begins at 9:30am?

### ISSUE THREAD

**Issue by CPSinSYSU** [CPSinSYSU/SHCD2017#1]
+ `8:55` 有很多`大兄弟`和`小姐姐`起不来床
+ 每周的课程最多就讲一个钟，不过课开了四节，因为可以多给点学分，大部分人应该也只是为了学分来的
+ 实验内容多开两节课也讲不完，而且受实验场地和器材影响，我们需要分组另外约时间在USI实验室展开实验
+ 如果大家同意的话，就把**第一节课推到9:30，少上一节**。

**Comment by chenweig** [comment]
Agree.               -------Team 5

**Comment by Daniel19950520** [comment]
Agree

**Comment by sysupoetry** [comment]
Agree
想问组号怎么看

**Comment by CPSinSYSU** [comment]
@sysupoetry You are Team 1 from now on
@Daniel19950520 You are Team 2
Don't forget to create [your group's Sidebar](https://github.com/CPSinSYSU/SHCD2017/wiki) please

**Comment by CPSinSYSU** [comment]
@shcd-group Please accept the invite from e-mail or Github....
Maybe you can click here: https://github.com/CPSinSYSU/SHCD2017/invitations for quick accept

**Comment by shcd-group** [comment]
Agree Team 3

**Comment by Lawrrencelrm** [comment]
Agree team4

**Comment by CPSinSYSU** [comment]
@Lawrrencelrm Yes, You are Team 4. I invite your group using this Github account(Lawrrencelrm)? Don't forget to e-mail me at chenshj35@qq.com

**Comment by CPSinSYSU** [comment]
@Lawrrencelrm Yes, You are Team 4. I invite your group using this Github account(Lawrrencelrm)? Don't forget to e-mail me at chenshj35@qq.com
Also!!! Don't forget to create [your group's Sidebar](https://github.com/CPSinSYSU/SHCD2017/wiki) please

**Comment by Kun-Lee** [comment]
Agree -- don't konw what team we have?

**Comment by SHCDstudents** [comment]
This's a good idea.I love learning.

**Comment by lzm316405** [comment]
niece

**Comment by lzm316405** [comment]
nice，good idea

**Comment by Durant35** [comment]
@Kun-Lee You are Team-6
@SHCDstudents You are Team-7
@14353160lzx You are Team-8
Please accept the invite from e-mail or Github....
Maybe you can click here: https://github.com/CPSinSYSU/SHCD2017/invitations for quick accept
Also!!! Don't forget to create [your group's Sidebar](https://github.com/CPSinSYSU/SHCD2017/wiki) please

**Comment by Durant35** [comment]
Classes will begin at 9:30am from Week-6

**Comment by Durant35** [comment]
@Kun-Lee Hurry up to create your team wiki on: https://github.com/CPSinSYSU/SHCD2017/wiki
