### ISSUE TITLE
whose username should be used when pulling the request

### ISSUE THREAD

**Issue by kontonpuku** [CPSinSYSU/SHCD2017#13]
I use my github username and password but error happen:
![image](http://imgsrc.baidu.com/forum/pic/item/a9c95934970a304e9c651c35d8c8a786cb175c94.jpg)
We are group 9, but we haven't get the branch. Shall we create our branch by ourselves?

**Comment by Goshin** [comment]
You should fork the repository firstly. Refer to the [wiki](https://github.com/CPSinSYSU/SHCD2017/wiki/03_Workflow).

**Comment by RH-Song** [comment]
If you have solved your problem, please remember to close the issue.
