### ISSUE TITLE
build-essential can't be install

### ISSUE THREAD

**Issue by Kun-Lee** [CPSinSYSU/SHCD2017#23]
说实话，一个英文标题够了吧。。
一开始安装的时候是显示 依赖关系以固定：dpkg dev（>= 1.） 差不多这样子，后来去网上查了各方牛鬼蛇神的神棍论，改了源，改成了
    网易163更新服务器（广东广州电信/联通千兆双线接入），包含其他开源镜像：
deb http://mirrors.163.com/ubuntu/ quantal main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ quantal-security main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ quantal-updates main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ quantal-proposed main restricted universe multiverse
deb http://mirrors.163.com/ubuntu/ quantal-backports main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ quantal main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ quantal-security main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ quantal-updates main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ quantal-proposed main restricted universe multiverse
deb-src http://mirrors.163.com/ubuntu/ quantal-backports main restricted universe multiverse
这个源，然后安装时找不到build-essenial这个软件包了

伸手问下怎么解决这个依赖问题

**Comment by Durant35** [comment]
假的吧。。。。换中科大（USTC）的源

**Comment by Goshin** [comment]
注意你的发行版版本。
注意 `sudo apt-get update`

**Comment by Kun-Lee** [comment]
感觉没犯什么错呀。。正正经经的换了个源地址，复制粘贴，去搜了个中科大的换，然后更新一下update各种404nofound，现在中科大的源地址加在了原本的源地址后面
想贴个图 来个something went really wrong那我也没办法了，贴点字

有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：
下列软件包有未满足的依赖关系：
 build-essential : 依赖: dpkg-dev (>= 1.13.5) 但是它将不会被安装
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
![image](https://cloud.githubusercontent.com/assets/6770853/25110826/8707b388-2419-11e7-9657-f5a0c9d5077b.png)

**Comment by Durant35** [comment]
你的Ubuntu是14.04还是16.04？
试试：`sudo apt-get install -f`？？？

**Comment by RH-Song** [comment]
我也是建议：
```
sudo apt-get install -f
```
首先，dpkg-dev是Debian系列的软件包开发工具，正常来说，它与build-essential要搭配使用的，可以参考Ubuntu官网的[这个说明](http://packages.ubuntu.com/zh-cn/trusty/dpkg-dev)。也就是说，正常是不会有冲突的。
再者，ibus是输入法框架吗？就是类似fcitx的东西？如果你使用搜狗输入法可以换成使用fcitx，干掉ibus都无所谓。
还是不行，最简单有效的方法是重装一下系统，因为估计你已经不知道哪个步骤把系统搞坏了。。。

**Comment by VincentCheungM** [comment]
你系统版本多少？

**Comment by VincentCheungM** [comment]
@Kun-Lee ref:https://askubuntu.com/questions/484750/why-build-essential-failed
