### ISSUE TITLE
Recommend to use current version of velodyne_viewer

### ISSUE THREAD

**Issue by Durant35** [CPSinSYSU/SHCD2017#3]
+ Previous version of velodyne_viewer in bad coding...

**Comment by RH-Song** [comment]
I also recommend the current one. The previous version has terrible coding style.

**Comment by VincentCheungM** [comment]
prj1lidar 里的 velodynedriver.cpp 乱码..GG

**Comment by huangyh43** [comment]
I'm lost.

**Comment by Durant35** [comment]
Finished...
