### ISSUE TITLE
A meeting for next week Class Schedule

### ISSUE THREAD

**Issue by Durant35** [CPSinSYSU/SHCD2017#4]
## Maybe need some time to talk together about how to measure data on LiDAR hardware benchmark

**Comment by Durant35** [comment]
Time？Find an relaxing time

**Comment by Durant35** [comment]
## 关于LiDAR性能指标测试计划（上半学期）
+ 学生自己采集数据
    + 每组同学自行考虑数据采集方案（需要TAs提前准备设想 考虑原理及方向，作为当周上课内容讲解），三天后提交到小组Wiki主页（`Proposal on Task: ....`章节），选取最好的小组周末来实验室进行实验。
    + 被选中的小组需要公布采集的数据集以及精确的场景参数描述（显然需要我们现场指导 辅助收集数据）；以该周任务公布Wiki的方式提交（`0?_Task: ....`），TA辅助修改
    + 第二周课程讲解方案实验情况，强调测试细节，发布测试任务
    + 没被选中的其他小组使用公布的数据集得到该项指标评估结果，评估方式/手段，以小组Wiki中 `Result on Task: ....`的章节方式提交；数据采集小组仅需提供数据采集答疑，数据评估作为可选任务
    + TA负责整合该周关于该性能指标的数据采集方案，各小组数据测试结果，最终的结论，并发布讨论issue；所有参与同学可以提出看法，作为修改意见整合进最终的结论，完成为期两周的任务。
    + 好处是能够锻炼学生的动手能力，不过只有在学与教对象间合作好才能减少各自的工作量，达成双赢。
+ TAs自行采集数据
    + TAs提前准备设想 考虑原理及方向，设计数据采集方案，整理成档，以Wiki（`0?_Task: ....`）和数据集的方式提交，并将方案，实验场景，实验情况作为当周讲解内容
    + 所有小组使用公布的数据集得到该项指标评估结果，评估方式/手段，以小组Wiki中 `Result on Task: ....`的章节方式提交
    + TA负责整合该周关于该性能指标的数据采集方案，各小组数据测试结果，最终的结论，并发布讨论issue；所有参与同学可以提出看法，作为修改意见整合进最终的结论
    + 第二周以答疑讨论为主，一项性能指标的任务周期仍为两周。
    + 按部就班的教育方式：具体的问题让学生具体解决，但是缺少了动手接触设备的机会，工作量各自分开，互不牵扯。

**Comment by RH-Song** [comment]
- 8-10周采数据，测性能指标；
- 11-16周分大组进行应用实践；
- 17周（根据进度调整，也可能提前一周开始）集体进行期末展示，以小组的形式进行。

**Comment by Durant35** [comment]
![image](https://cloud.githubusercontent.com/assets/6770853/24705078/e223329c-1a3c-11e7-839a-f4e58a3c6722.png)

**Comment by Durant35** [comment]
## Meeting result
- 8-10周采数据，测性能指标；
- 11-16周分大组进行应用实践；
- 17周（根据进度调整，也可能提前一周开始）集体进行期末展示，以小组的形式进行。

@kaihuangtum
