### ISSUE TITLE
error on cmake parameter

### ISSUE THREAD

**Issue by VincentCheungM** [CPSinSYSU/SHCD2017#5]
From the step 2 in wiki, the path of `install prefix doesn't exist`, is "`pwd`" should be "`$(pwd)`"? I have not tried yet, @Durant35 
```shell
cmake -DCMAKE_INSTALL_PREFIX=`pwd`/../ ..
```

**Comment by Durant35** [comment]
I should be like following:
```shell
`pwd`
```

**Comment by Durant35** [comment]
## Finding: It will be trouble in some strange path
+ like: with space in path

**Comment by Durant35** [comment]
## Following is a better way
```shell
cmake -DCMAKE_INSTALL_PREFIX="$(pwd)/../" ..
```

**Comment by Kun-Lee** [comment]
why a problem "directory does not appear to contain CMakeLists.txt."?

**Comment by Durant35** [comment]
cmake depends on a CMakeLists.txt, and cmake will find the current directory for this CMakeLists.txt. So, when you run cmake, check if current directory has one or not(error occurs). Besides, we use `cmake ..` in our project because we want to build out-of-source(in an independent build directory), and the CMakeLists.txt located at this build parent directory, so we use `..`

**Comment by Kun-Lee** [comment]
why a problem "make: *** No targets specified and no makefile found.  Stop."?
and should I Configure the experimental environment in the file "Velodyne_viewer"?

**Comment by Durant35** [comment]
cmake finally generate a `Makefile` if no error occurs(in the directory you run `cmake`), while Makefile is use by `make`. `make` is very similar to `cmake`, instead finding `Makefile`....
All this is mentioned in this [Wiki](https://github.com/CPSinSYSU/SHCD2017/wiki/02_LiDAR-Driver), hope you develop a habit: read what clearly first, understand why second(Google will help), then how to do becomes easy.

**Comment by Kun-Lee** [comment]
No,  I follow your steps without a "Makefile" file...

**Comment by Kun-Lee** [comment]
Only a "CMakefiles"

**Comment by Durant35** [comment]
You make sure that there is no any error occurred in your `cmake` command??? maybe lost some dependencies

**Comment by Kun-Lee** [comment]
really; I can't find the problem....I only have Cmakefiles;;

**Comment by Kun-Lee** [comment]
I cmake the file "CmakeList.txt" and get CMakeFiles and a CMakeCache.txt ,en

**Comment by Durant35** [comment]
You can put some screenshot(directly ctrl+V to upload here...), I want to see your `cmake` print info, your currrent directory `ls` info

**Comment by Kun-Lee** [comment]
I send a mail of qq I'm sorry.
![image](https://cloud.githubusercontent.com/assets/6770853/24648576/9ecc7c4c-1956-11e7-8b5d-b4b54df9f49a.png)

**Comment by Durant35** [comment]
@Kun-Lee Please do read the Wiki carefully first.... follow the wiki, do not meet any problem with great probability.....Thanks!

**Comment by Kun-Lee** [comment]
a problem "Cmake error at Cmakelists.txt:36" is "add_subdirectory(src bin)" why do with?plz.
![image](https://cloud.githubusercontent.com/assets/6770853/24648521/6ebff3b2-1956-11e7-8d40-ab8d5114d161.png)
![image](https://cloud.githubusercontent.com/assets/6770853/24648634/cc552574-1956-11e7-82cf-492145b8b7f4.png)

**Comment by Durant35** [comment]
请截图吧 最好包括运行的命令 所在目录情况 运行结果 谢谢

**Comment by Durant35** [comment]
@Kun-Lee  Why you said: `a problem "Cmake error at Cmakelists.txt:36"`????

**Comment by Kun-Lee** [comment]
It was before I built the file "build" outside.Now I put "build" in "Velodyne_viewer".it has new error.

**Comment by Durant35** [comment]
I think you can easily read the above `CMake Error` and install corresponding dependency(glut) as [Wiki](https://github.com/CPSinSYSU/SHCD2017/wiki/02_LiDAR-Driver) said to fix your problem....
![image](https://cloud.githubusercontent.com/assets/6770853/24648977/0fb51dd2-1958-11e7-8eb3-ff922fd78437.png)
Don't do something wrong that make you in trouble before understanding the command `cmake & make`

**Comment by Kun-Lee** [comment]
no no no u see;

**Comment by Kun-Lee** [comment]
![Uploading image.png…]()

**Comment by Kun-Lee** [comment]
![image](https://cloud.githubusercontent.com/assets/22704716/24649230/f35d7df4-1958-11e7-904d-8e4ff36de76a.png)
no no no  you see;

**Comment by Durant35** [comment]
![image](https://cloud.githubusercontent.com/assets/6770853/24649360/5dda643a-1959-11e7-91ca-61274b14c6a2.png)

**Comment by Kun-Lee** [comment]
why can't python?

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/rT.AddKL2SdojqXOY16LGrhF0ZNIg0vm14Y1CrV11qE!/b/dIMBAAAAAAAA&bo=UQJkAAAAAAADABI!&rf=viewer_4)

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/rT.AddKL2SdojqXOY16LGrhF0ZNIg0vm14Y1CrV11qE!/b/dIMBAAAAAAAA&bo=UQJkAAAAAAADABI!&rf=viewer_4)
why can't python?

**Comment by Durant35** [comment]
@Kun-Lee https://github.com/CPSinSYSU/SHCD2017/issues/6

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/bzED2vech9Y81Q1wrRCXs3ipngFh4shvFKihdd4gJJ8!/b/dFYBAAAAAAAA&bo=nAMEAgAAAAADB7s!&rf=viewer_4)
while make and make install error 1 failed .this problem ?

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/bzED2vech9Y81Q1wrRCXs3ipngFh4shvFKihdd4gJJ8!/b/dFYBAAAAAAAA&bo=nAMEAgAAAAADB7s!&rf=viewer_4)

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/bzED2vech9Y81Q1wrRCXs3ipngFh4shvFKihdd4gJJ8!/b/dFYBAAAAAAAA&bo=nAMEAgAAAAADALw!&rf=viewer_4)

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/bzED2vech9Y81Q1wrRCXs3ipngFh4shvFKihdd4gJJ8!/b/dFYBAAAAAAAA&bo=nAMEAgAAAAADALw!&rf=viewer_4)
while make and make install an error appear.I can't understand here?

**Comment by Durant35** [comment]
无所谓 能跑就行了。。。程序已经成功生成了

**Comment by Kun-Lee** [comment]
可是很奇怪的是 我后面 点开.pcap跑出一个wireshake 点开view那个也只有全屏都是黑的  没有一个点？不是这个错误？

**Comment by Durant35** [comment]
给你们的代码不可能实现了解析，需要你们自己实现

**Comment by VincentCheungM** [comment]
@Kun-Lee 你是说点开pcap跑出一个wireshark，点开view只有一个矩形框？你需要通过运行那个python脚本来回拨pcap，同时打开viewer才有那个点。至于你python报的错就是系统没有numpy这个库。

**Comment by Kun-Lee** [comment]
是先运行viewer放着 然后按照那个步骤来运行python脚本吗？

**Comment by VincentCheungM** [comment]
@Kun-Lee viewer只是viewer。还需要数据才能显示，从群众中来到群众中去，数据从`pcap`中来到`viewer`中去，那个python脚本就用于播放数据。
