### ISSUE TITLE
error occurs while using python replay scripts

### ISSUE THREAD

**Issue by Durant35** [CPSinSYSU/SHCD2017#6]
![image](https://cloud.githubusercontent.com/assets/6770853/24651363/17252726-1960-11e7-9808-7853c9cb9f73.png)

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/rT.AddKL2SdojqXOY16LGrhF0ZNIg0vm14Y1CrV11qE!/b/dIMBAAAAAAAA&bo=UQJkAAAAAAADABI!&rf=viewer_4)
sorry! why can't python here?

**Comment by Durant35** [comment]
+ some dependencies miss for this python script, here install `python-numpy`
```
sudo apt-get install python-numpy
```

**Comment by Kun-Lee** [comment]
![](http://a1.qpic.cn/psb?/V10xhQuy3m7suY/.1sAHVd7zrUVwHra5kmWNZ7.VM*LaJVjJ9sOsjs5SuE!/b/dGgBAAAAAAAA&bo=4QFaAAAAAAADB5g!&rf=viewer_4)
have something wrong here?

**Comment by JontyLu** [comment]
![image](https://cloud.githubusercontent.com/assets/25874085/24989314/4174e6da-203e-11e7-9aac-ee09f6d7824b.png)
what's going on ? how to deal with?

**Comment by JontyLu** [comment]
![image](https://cloud.githubusercontent.com/assets/25874085/24989331/660fafac-203e-11e7-9e10-7edb4e7b698f.png)
what's going on? how to deal with it?

**Comment by Goshin** [comment]
@JontyLu Have you ever tried `./run.sh` ?

**Comment by JontyLu** [comment]
@Goshin now I know the problem.But there is still an error that 
>  set socket thread sched ERROR,status=22

**Comment by Kun-Lee** [comment]
why ./run.sh with"Permission denied"?
![image](https://cloud.githubusercontent.com/assets/6770853/25035847/bc704926-2122-11e7-8cf9-2968134273a2.png)

**Comment by Kun-Lee** [comment]
![Uploading image.png…]()

**Comment by Durant35** [comment]
@Kun-Lee can you upload some snapshot for your problem?
Besides, **Could not read config file**, you should fix this first

**Comment by Durant35** [comment]
@JontyLu  could you upload thesnapshot for your problem? Actually, this maybe not the critical problem

**Comment by Durant35** [comment]
@Kun-Lee You must check that you have successfully build your project(`Velodyne_viewer`) and install it in this bin dir....
Beside, you should learn some `shell script` in reading the `run.sh` script, Google it please, all these are simple as well as direct problem
